[project]
name = "hello-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "prasojo jiwandono", email = "prasojoforwork@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "slowapi>=0.1.10",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
hello-fastapi = "hello_fastapi:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
